easy-planif/cal/urls.py
from django.urls import path
from . import views

app_name = 'cal'
urlpatterns = [
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('calendar/event/new/', views.create_event, name='event_new'),
    path('global_calendar', views.GlobalCalendarView.as_view(), name='global_calendar'),
    path('planning', views.PlanningView.as_view(), name='planning'),
    path('planning/event/update', views.update_event, name='planning_event_update'),
    path('bookingTypes', views.BookingTypeView.as_view(), name='booking_type'),
    path('addBookingType', views.add_booking_type, name='booking_type'),
    path('bookings', views.BookingsView.as_view(), name='bookings'),
    path('addBooking', views.add_booking, name='add_booking'),
]

easy-planif/easyplanif/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('accounts/', include('accounts.urls')),
    path("accounts/", include('django.contrib.auth.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
    path('', include('cal.urls')),
    path('', include('accounts.urls')),
    path('', include('tasks.urls')),
]

easy-planif/cal/models.py
from accounts.models import CustomUser
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from tasks.models import Tasks, Authorizations

class Event(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    tasks = models.ForeignKey(Tasks, on_delete=models.CASCADE, blank=True, null=True)
    is_available = models.BooleanField(default=True)
    date = models.DateTimeField()

    class Meta:
        permissions = [
            ('assign_task', 'Assign a Task'),
        ]

    def clean(self):
        super().clean()

        if self.tasks is not None and self.is_available:
            raise ValidationError({"content": "Event cannot have a task and be available"})

        if not self.is_available:
            if self.tasks is None:
                raise ValidationError({"content": "Event must have a task is not available"})
            auth = Authorizations.objects.filter(user=self.user, task=self.tasks)
            if len(auth) == 0:
                raise ValidationError({"content": "Unauthorized"})

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

class BookingType(models.Model):
    booking_type = models.CharField(max_length=100)

    def __str__(self):
        return self.booking_type

class Booking(models.Model):
    booking_name = models.CharField(max_length=100)
    booking_type = models.ForeignKey(BookingType, on_delete=models.SET_NULL, blank=True, null=True)
    date = models.DateField()
    date_report = models.DateField(blank=True, null=True)
    come_all_weather = models.BooleanField(default=False)
    hour_start = models.TimeField()
    hour_end = models.TimeField()
    group_leader_name = models.CharField(max_length=100)
    group_leader_address = models.TextField()
    group_leader_email = models.EmailField()
    group_leader_phone = models.CharField(max_length=100, blank=True, null=True)
    nbr_adult = models.PositiveIntegerField()
    nbr_child = models.PositiveIntegerField()
    nbr_wheelchair = models.PositiveIntegerField(blank=True, null=True)
    price_adult = models.FloatField(validators=[MinValueValidator(0)], default=0)
    price_child = models.FloatField(validators=[MinValueValidator(0)], default=0)
    meal_included = models.BooleanField(default=False)
    meal_price_adult = models.FloatField(validators=[MinValueValidator(0)], default=0)
    meal_price_child = models.FloatField(validators=[MinValueValidator(0)], default=0)
    price_total = models.FloatField()
    comments = models.TextField(blank=True, null=True)
    meal_comments = models.TextField(blank=True, null=True)
    last_author = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        permissions = [
            ('bookings_view', 'View bookings'),
            ('bookings_manager', 'Manage bookings'),
        ]

    def clean(self):
        super().clean()
        if self.hour_end < self.hour_start:
            raise ValidationError({"hour_start": "Booking start must be before booking end"})

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

easy-planif/cal/forms.py
from django.forms import ModelForm, DateInput
from django import forms
from .models import Event, BookingType, Booking


class EventForm(ModelForm):
  class Meta:
    model = Event
    widgets = {
      'date': DateInput(format='%d-%m-%Y'),
    }
    fields = ['is_available', 'date']

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    self.fields['date'].input_formats = ('%d-%m-%Y',)

class AddBookingTypeForm(ModelForm):
    class Meta:
        model = BookingType
        fields = '__all__'

class AddBookingForm(ModelForm):
    class Meta:
        model = Booking
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'date_report': forms.DateInput(attrs={'type': 'date'}),
            'hour_start': forms.TimeInput(attrs={'type':'time','step':60}),
            'hour_end': forms.TimeInput(attrs={'type':'time','step':60})
        }
        exclude = ['last_author']

easy-planif/cal/views.py
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.contrib.auth.decorators import permission_required
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views import generic
from django.utils.safestring import mark_safe
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied

from .forms import EventForm, AddBookingTypeForm, AddBookingForm
from .models import Event, BookingType, Booking
from .utils import Calendar, GlobalCalendar, PlanningCalendar, BookingsCalendar
from tasks.models import Tasks
from datetime import timedelta
from .helpers import get_date, prev_month, next_month, get_date_week, prev_week, next_week


class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        cal = Calendar(self.request.user, d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)

        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)

        return context

class GlobalCalendarView(generic.ListView):
    model = Event
    template_name = 'cal/global_calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        today = get_date_week(self.request.GET.get('week_date', None))
        monday = today - timedelta(days=today.weekday())

        week_dates = [monday + timedelta(days=i) for i in range(7)]

        cal = GlobalCalendar()
        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatweek(week_dates)
        context['calendar'] = mark_safe(html_cal)

        context['prev_week'] = prev_week(today)
        context['next_week'] = next_week(today)

        return context

class PlanningView(PermissionRequiredMixin, generic.ListView):
    model = Event
    template_name = 'cal/planning.html'
    permission_required = 'cal.assign_task'
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # use today's date for the calendar
        today = get_date_week(self.request.GET.get('week_date', None))
        monday = today - timedelta(days=today.weekday())

        week_dates = [monday + timedelta(days=i) for i in range(7)]

        tasks = Tasks.objects.all()

        cal = PlanningCalendar()
        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatweek(week_dates,  context['view'].request)
        context['calendar'] = mark_safe(html_cal)
        context['tasks'] = tasks
        context['prev_week'] = prev_week(today)
        context['next_week'] = next_week(today)

        return context

class BookingsView(PermissionRequiredMixin, generic.ListView):
    model = Booking
    template_name = 'cal/bookings.html'
    permission_required = 'cal.bookings_view'
    raise_exception = True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # use today's date for the calendar
        d = get_date(self.request.GET.get('month', None))

        # Instantiate our calendar class with today's year and date
        cal = BookingsCalendar(d.year, d.month)

        # Call the formatmonth method, which returns our calendar as a table
        html_cal = cal.formatmonth(withyear=True)
        context['bookings'] = mark_safe(html_cal)

        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)

        return context

@permission_required('cal.bookings_manager', raise_exception=True)
def add_booking(request):
    if request.method == "POST":
        form = AddBookingForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/bookings")
    else:
        form = AddBookingForm()
    return render(request, "cal/add_booking.html", {"form": form})

class BookingTypeView(generic.ListView):
    model = BookingType
    template_name = 'cal/booking_type.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            raise PermissionDenied("Staff members only.")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = '<ul class="list-group">'
        for t in BookingType.objects.all():
            d += f'<li class="list-group-item"> {t.booking_type} </li>'
        d += '</ul>'
        context['booking_types'] = mark_safe(d)
        return context

@staff_member_required
def add_booking_type(request):
    if request.method == "POST":
        form = AddBookingTypeForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/bookingTypes")
    else:
        form = AddBookingTypeForm()
    return render(request, "cal/add_booking_type.html", {"form": form})

def create_event(request):
    instance = Event()
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        event = form.save(commit=False)
        event.user = request.user
        event.save()
        return HttpResponse(status=201)
    return HttpResponseBadRequest()

@permission_required('cal.assign_task', raise_exception=True)
def update_event(request):
    event = Event.objects.filter(id=request.POST.get('event_id'))[0]
    event.is_available = False
    event.tasks = Tasks.objects.filter(id=request.POST.get('task_id'))[0]
    event.save()
    return_path = "/planning"
    has_week_date = False
    if request.POST['week_date'] != 'None':
        return_path += '?week_date=' + request.POST['week_date']
        has_week_date = True
    if request.POST['task'] != 'None':
        if has_week_date:
            return_path += '&task=' + request.POST['task']
        else:
            return_path += '?task=' + request.POST['task']
    return HttpResponseRedirect(return_path)

easy-planif/cal/templates/cal/add_booking.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <title>Django Calendar App</title>
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  <div class="container">
  {% if user.is_authenticated %}
  {% include "menu.html" %}
  <div class="clearfix">
  <form action="/addBooking" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>
  </div>
  {% endif %}
  </div>
</body>
</html>

easy-planif/cal/templates/cal/add_booking_type.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <title>Django Calendar App</title>
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  <div class="container">
  {% if user.is_authenticated %}
  {% include "menu.html" %}
  <div class="clearfix">
  <form action="/addBookingType" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="OK" %}
  </form>
  </div>
  {% endif %}
  </div>
</body>
</html>

easy-planif/cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <title>Django Calendar App</title>
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <script>
    var csrftoken = '{{ csrf_token }}';
    function createAvailableEvent(date){
        xhr = new XMLHttpRequest();
        xhr.open("POST", "event/new/");
        //xhr.setRequestHeader("Content-Type", "application/json");
        xhr.setRequestHeader("Content-type","application/x-www-form-urlencoded");
        xhr.setRequestHeader('X-CSRFToken', csrftoken);
        body = "is_available=true&date="+date;
        xhr.onload = () => {
          if(xhr.status === 201) {
            location.reload();
          } else {
            alert("Event was not created!");
          }
        };
        xhr.send(body);
    }
  </script>
</head>
<body>
  <div class="container">
  {% if user.is_authenticated %}
  {% include "menu.html" %} 
  {% block content %}
  {% endblock %}

  {% block script %}
  {% endblock %}
  {% endif %}
  </div>
</body>
</html>

easy-planif/cal/templates/cal/booking_type.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
  <title>Django Calendar App</title>
  {% load django_bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>
  <div class="container">
  {% if user.is_authenticated %}
  {% include "menu.html" %}
  <div class="clearfix">
  <a href="addBookingType">Add Booking Type</a>
  </div>
  <div class="clearfix">
  {{ booking_types }}
  </div>
  {% endif %}
  </div>
</body>
</html>

easy-planif/cal/templates/cal/bookings.html
{% extends 'cal/base.html' %}
{% block content %}
<div class="clearfix">
    <nav class="navbar">
	<a class="btn btn-info left" href="{% url 'cal:bookings' %}?{{ prev_month }}"> Previous Month </a>
    {% if perms.cal.bookings_view %}
    <a class="btn btn-secondary center" href=addBooking> Add booking </a>
    {% endif %}
	<a class="btn btn-info right" href="{% url 'cal:bookings' %}?{{ next_month }}"> Next Month </a>
    </nav>
</div>
{{ bookings }}
{% endblock %}

easy-planif/cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}
{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
</div>
{{ calendar }}
{% endblock %}

easy-planif/cal/templates/cal/dropdown_planning.html
<form action="/planning/event/update" method="POST">
    {% csrf_token %}
    <input type="hidden" name="event_id" value={{event_id}}>
    <input type="hidden" name="week_date" value={{week_date}}>
    <input type="hidden" name="task" value={{task}}>
    <select name="task_id" id="task_id" required onchange="this.form.submit()">
        <option value="" disabled selected>---</option>
        {% for task in tasks %}
            <option value="{{task.id}}">{{task.task_name}}</option>
        {% endfor %}
    </select>
</form>

easy-planif/cal/templates/cal/global_calendar.html
{% extends 'cal/base.html' %}
{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:global_calendar' %}?{{ prev_week }}"> Previous Week </a>
	<a class="btn btn-info right" href="{% url 'cal:global_calendar' %}?{{ next_week }}"> Next Week </a>
</div>
{{ calendar }}
{% endblock %}

easy-planif/cal/templates/cal/planning.html
{% extends 'cal/base.html' %}
{% block content %}
<div class="clearfix">
    <nav class="navbar">
	<a class="btn btn-info left" href="{% url 'cal:planning' %}?{{ prev_week }}"> Previous Week </a>
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle center" type="button" id="dropdownTasks" data-bs-toggle="dropdown" aria-expanded="true">
                Tasks
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownTasks">
            {% for task in tasks %}
            <li><a id=task-{{task.id}} class="dropdown-item" href="#">{{ task }}</a></li>
            <script>
                // What you want to add – change this as needed
                newParam = 'task';
                newValue = {{ task.id | safe }};
                // Build the new URL
                url = new URL(window.location);
                url.searchParams.set(newParam, newValue);
                // Update the link’s href attribute
                document.getElementById('task-{{task.id}}').href = url.toString();
            </script>
            {% endfor %}
        </ul>
    </div>
	<a class="btn btn-info right" href="{% url 'cal:planning' %}?{{ next_week }}"> Next Week </a>
    </nav>
</div>
{{ calendar }}
{% endblock %}